dataset:
  name: nerfstudio
  tag: campanile
  downscale_factor: 2
model:
  name: dbw
  mesh:
    n_blocks: 10
    S_world: 1
    R_world: [-90, 20, 0]
    T_world: [-1.25, 0, -0.25]
    txt_size: 256
    T_range: [1, 0.5, 1]
  renderer:
    faces_per_pixel: 10
    cameras:
      name: perspective
    detach_bary: True
    z_clip: 0.001
  rend_optim:
    coarse_learning: 250
    decimate_txt: 125
    decimate_factor: 8
    kill_blocks: True
    decouple_rendering: True
    opacity_noise: True
  loss:
    rgb_weight: 1
    perceptual_weight: 0.1
    parsimony_weight: 0.01
    tv_weight: 0.1
    overlap_weight: 1
training:
  batch_size: 4
  n_workers: 4
  optimizer:
    name: adam
    lr: 5.0e-3
    texture:
      lr: 5.0e-2
  scheduler:
    name: multi_step
    gamma: [0.1, 0.1]
    milestones: [300]
  n_epoches: 320
  train_stat_interval: 50
  val_stat_interval: 100
  seed: 222213
  visualizer: 
    name: visdom
    port: 8888
  resume:
